disecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("invoice.urls")),
]

invoice/urls.py
from django.contrib import admin
from django.urls import path
from .views import InvoiceListView, createInvoice, generate_PDF, view_PDF

app_name = 'invoice'
urlpatterns = [
    path('', InvoiceListView.as_view(), name="invoice-list"),
    path('create/', createInvoice, name="invoice-create"),
    path('invoice-detail/<id>', view_PDF, name='invoice-detail'),
    path('invoice-download/<id>', generate_PDF, name='invoice-download')
]

invoice/models.py
from django.db import models
import datetime

# Create your models here.
    
class Invoice(models.Model):
    customer = models.CharField(max_length=100)
    customer_email = models.EmailField(null=True,blank=True)
    billing_address = models.TextField(null=True,blank=True)
    date = models.DateField()
    due_date = models.DateField(null=True,blank=True)
    message = models.TextField(default="this is a default message.")
    total_amount = models.DecimalField(max_digits=9,decimal_places=2,blank=True,null=True)

    def __str__(self):
        return str(self.customer)
    
    def get_status(self):
        return self.status


class LineItem(models.Model):
    customer = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    service = models.TextField()
    description= models.TextField()
    quantity= models.IntegerField()
    rate = models.DecimalField(max_digits=9,decimal_places=2)
    amount = models.DecimalField(max_digits=9,decimal_places=2)

    def __str__(self):
        return str(self.customer)
        

invoice/forms.py
from email import message
from django import forms
from django.forms import formset_factory
from .models import Invoice


class InvoiceForm(forms.Form):
    customer = forms.CharField(
        label='Customer',
        widget= forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Customer Name',
            'rows':1
        })
    )
    customer_email = forms.CharField(
        label='Customer Email',
        widget=forms.TextInput(attrs={
            'class':'form-control',
            'placeholder': 'customer@emailid.com',
            'rows':1
        })
    )

    billing_address = forms.CharField(
         label='Billing Address',
         widget=forms.TextInput(attrs={
             'class': 'form-control',
             'placeholder':'',
             'rows':1
         })
    )

    message = forms.CharField(
        label='Message/Note',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'message',
            'rows':1
        })
    )

class LineItemForm(forms.Form):
    
    service = forms.CharField(
        label='Service/Product',
        widget=forms.TextInput(attrs={
            'class': 'form-control input',
            'placeholder': 'Service Name'
        })
    )
    description = forms.CharField(
        label='Description',
        widget=forms.TextInput(attrs={
            'class': 'form-control input',
            'placeholder': 'Product description',
            "rows":1
        })
    )
    quantity = forms.IntegerField(
        label='Qty',
        widget=forms.TextInput(attrs={
            'class': 'form-control input quantity',
            'placeholder': 'Quantity'
        }) #quantity should not be less than one
    )
    rate = forms.DecimalField(
        label='Rate $',
        widget=forms.TextInput(attrs={
            'class': 'form-control input rate',
            'placeholder': 'Rate'
        })
    )
   
    
LineItemFormset = formset_factory(LineItemForm, extra=1)

invoice/views.py
from django.shortcuts import render,redirect,get_object_or_404,reverse
from django.template.loader import get_template
from django.http import HttpResponse
from django.views import View
from .models import LineItem,Invoice
from .forms import LineItemFormset,InvoiceForm

import pdfkit

class InvoiceListView(View):
    def get(self,*args,**kwargs):
        invoices = Invoice.objects.all()
        context = {
            "invoices":invoices,
        }

        return render(self.request,'invoice/invoice-list.html',context)

def createInvoice(request):
    heading_message = 'Formset Demo'
    if request.method == 'GET':
        formset= LineItemFormset(request.GET or None)
        form = InvoiceForm(request.GET or None)
    elif request.method == 'POST':
        formset = LineItemFormset(request.POST)
        form = InvoiceForm(request.POST)

        if form.is_valid():
            invoice = Invoice.objects.create(customer=form.data["customer"],
                    customer_email=form.data["customer_email"],
                    billing_address = form.data["billing_address"],
                    date=form.data["date"],
                    due_date=form.data["due_date"], 
                    message=form.data["message"],
                    )
        # invoice.save()

        if formset.is_valid():
            total=0
            for form in formset:
                service = form.cleaned_data.get('service')
                description = form.cleaned_data.get('description')
                quantity = form.cleaned_data.get('quantity')
                rate = form.cleaned_data.get('rate')
                if service and description and quantity and rate:
                    amount= float(rate)*float(quantity)
                    total += amount
                    LineItem(customer=invoice,
                                service=service,
                                description=description,
                                quantity=quantity,
                                rate=rate,
                                amount=amount).save()
            invoice.total_amount = total
            invoice.save()
            try:
                generate_PDF(request,id=invoice.id)
            except Exception as e:
                print(f"********{e}******")
            return redirect('/')
    
    context ={
        "title":"Invoice Generator",
        "formset": formset,
        "form": form
    }
    return render(request,'invoice/invoice-create.html',context)

def view_PDF(request, id=None):
    invoice = get_object_or_404(Invoice,id=id)
    lineitem = invoice.lineitem_set.all()

    context = {
        "company":{
            "name": "Virtual Company Ltd.",
            "address": "23th Street, Zbcxyz",
            "phone": "+91 XXXX-XX-XXXX",
            "email": "abc@xompany.com",
        },
        "invoice_id": invoice.id,
        "invoice_total": invoice.total_amount,
        "customer": invoice.customer,
        "customer_email":invoice.customer_email,
        "date": invoice.date,
        "due_date":invoice.due_date,
        "billing_address":invoice.billing_address,
        "message": invoice.billing_address,
        "lineitem":lineitem,
    }
    return render(request,'invoice/pdf_template.html',context)

def generate_PDF(request,id):
    pdf = pdfkit.from_url(request.build_absolute_uri(reverse('invoice:invoice-detail',args=[id])),False)
    response= HttpResponse(pdf,content_type='application/pdf')
    response['Content-Disposition']='attachment; filename="invoice.pdf"'

    return response


def view_404(request, *args, **kwags):
    return redirect('invoice:invoice-list')

invoice/templates/invoice/base.html
<!doctype html>{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
     <link href="{% static 'css/bulma-calendar.min.css' %}" rel="stylesheet">
     <link href="{% static 'js/bulma-calendar.min.js' %}" rel="stylesheet">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
     {% block custom_css %}{% endblock %}
    <title>Django Library App</title>
</head>
<body>
     
    <div class="container">
                {% block content %}
                {% endblock %}
            </div>
    <footer class="footer">
        <center><p class="has-text-weight-bold">Invoice Generator</p>
        </center>
        </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
     {% block custom_js %}{% endblock %}
</body>

invoice/templates/invoice/invoice-create.html
{% extends "invoice/base.html" %}{% load bulma_tags %}
{% block content %}
<br>
<section class="hero is-fullheight">
    <div class="container">
        <div class="card white-ter">
            <div class="hero-body">
                <form class="" method="POST" action="">{% csrf_token %}
                    <div class="columns is-centered">
                        <div class="column is-one-third">
                            {{form.customer|bulma}}
                        </div>

                        <div class="column is-one-third">
                            {{form.customer_email|bulma}}
                        </div>
                        <div class="column is-one-third">
                            {{form.message|bulma}}
                        </div>
                    </div>
                    <div class="columns is-centered">
                        <div class="column is-one-third">
                            {{form.billing_address|bulma}}
                        </div>
                        <div class="column is-one-third">
                            date: <input class="input" type="date" name="date">
                        </div>
                        <div class="column is-one-third">
                            due-date: <input class="input" type="date" name="due_date">
                        </div>
                    </div>


                    <table class="table is-fullwidth is-bordered is-hoverable is-striped">
                        <tbody>
                            <thead>
                                <tr>
                                    <th>Product/item</th>
                                    <th>Description</th>
                                    <th>QTY</th>
                                    <th>RATE</th>
                                    <th>AMOUNT&#x20B9;</th>
                                    <th>ADD</th>
                                </tr>
                                {{ formset.management_form }}
                                {% for form in formset %}
                                <tr>
                                    <td>{{form.service}}</td>
                                    <td>{{form.description}}</td>
                                    <td>{{form.quantity}}</td>
                                    <td>{{form.rate}}</td>
                                    <td class="amount"></td>
                                    <td>
                                        <div class="input-group-append">
                                            <button
                                                class="button is-small btn btn-success add-form-row">+</button>&nbsp;
                                            <!-- <button class="button is-small btn btn-warning remove-form-row">-</button> -->
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            </thead>
                        </tbody>

                    </table>
                    <div class="row spacer">
                        <div class="col-4 offset-2">
                            <button type="submit" class="button btn btn-block is-info is-half">Create</button>
                        </div>
                    </div>
                    <br>
                    <div class="columns">
                        <div class="column">
                            <h3 class="title is-4">Total(&#x20B9;): <span id="total"></span></h3>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>



{% endblock %}

{% block custom_js %}
<script type="text/javascript">
    $('table input').on("input", function () {
        var total = []
        var $tr = $(this).closest('tr');
        var textValue1 = $("input.rate", $tr).val();
        var textValue2 = $('input.quantity', $tr).val();
        amt = textValue1 * textValue2;
        // console.log(amt);
        $('.amount', $tr).html(amt);
        calc_total();
    });

    function calc_total() {
        var sum = 0;
        $(".amount").each(function () {
            sum += parseFloat($(this).text());
        });
        console.log(sum);
        $('#total').text(sum);
    }
</script>


<script type="text/javascript">
    function updateElementIndex(el, prefix, ndx) {
        var id_regex = new RegExp('(' + prefix + '-\\d+)');
        var replacement = prefix + '-' + ndx;
        if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
        if (el.id) el.id = el.id.replace(id_regex, replacement);
        if (el.name) el.name = el.name.replace(id_regex, replacement);
    }
    function cloneMore(selector, prefix) {
        var newElement = $(selector).clone(true);
        console.log(newElement);
        var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
        newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function () {
            var name = $(this).attr('name')
            if (name) {
                name = name.replace('-' + (total - 1) + '-', '-' + total + '-');
                var id = 'id_' + name;
                $(this).attr({ 'name': name, 'id': id }).val('').removeAttr('checked');
            }
        });
        newElement.find('label').each(function () {
            var forValue = $(this).attr('for');
            if (forValue) {
                forValue = forValue.replace('-' + (total - 1) + '-', '-' + total + '-');
                $(this).attr({ 'for': forValue });
            }
        });
        total++;
        $('#id_' + prefix + '-TOTAL_FORMS').val(total);
        $(selector).after(newElement);
        // $("div.form-row.button.is-primary").not(":last").hide();
        // var conditionRow = $('.form-row:not(:last)');
        // conditionRow.find('.button.is-primary')
        // .hide();
        // .removeClass('btn-success').addClass('btn-danger')
        // .removeClass('add-form-row').addClass('remove-form-row')
        // .html('-');
        return false;
    }
    function deleteForm(prefix, btn) {
        var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
        if (total > 1) {
            btn.closest('.form-row').remove();
            var forms = $('.form-row');
            $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
            for (var i = 0, formCount = forms.length; i < formCount; i++) {
                $(forms.get(i)).find(':input').each(function () {
                    updateElementIndex(this, prefix, i);
                });
            }
        }
        return false;
    }
    $(document).on('click', '.add-form-row', function (e) {
        e.preventDefault();
        cloneMore('table tr:last', 'form');
        return false;
    });
    $(document).on('click', '.remove-form-row', function (e) {
        e.preventDefault();
        deleteForm('form', $(this));
        return false;
    });

</script>
{% endblock %}

invoice/templates/invoice/invoice-list.html
{% extends 'invoice/base.html' %}
{% block content %}
<div class="columns is-centered has-text-centered">
    <div class="column is-half">
        <div class="card has-background-white-ter">
            <h1 class="title is-3"></h1>
        </div>
    </div>
</div>
<form action="{% url 'invoice:invoice-list' %}" method="post">{% csrf_token %}
    <div class="card">
        <header class="card-header">
            <p class="card-header-title">
                All Invoices &nbsp;<button class="button is-rounded is-info">
                    <a href="{% url 'invoice:invoice-create' %}" class="has-text-white">Create Invoice</a></button>
            </p>
        </header>
        <div class="card-content">
            <div class="content">

                <table class="table is-fullwidth is-bordered is-hoverable is-striped">
                    <tbody>
                        <thead>
                            <tr>
                                <th>INVOICE</th>
                                <th>CUSTOMER</th>
                                <th>DATE</th>
                                <th>DUE DATE</th>
                                <th>TOTAL</th>
                                <th>View</th>
                                <th>DOWNLOAD</th>

                            </tr>
                        </thead>
                        {% for invoice in invoices %}
                        <tr>
                            </td>
                            <td width="1%">#{{invoice.id}}</td>
                            <td width="9%">{{invoice.customer}}</td>
                            <td> {{invoice.date}}</td>
                            <td> {{invoice.due_date}} </td>
                            <td>{{invoice.total_amount}}</td>
                            <td width="1%"><a href="{% url 'invoice:invoice-detail' id=invoice.id %}">
                                <div class="button is-small is-info">View</div>
                            </a></td>
                            <td width="1%"><a href="{% url 'invoice:invoice-download' id=invoice.id %}">Download</a></td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>

            </div>
        </div>
    </div><br /><br /><br />
</form>

{% endblock content %}

invoice/templates/invoice/pdf_template.html
<!DOCTYPE html>{% load static%}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Example 2</title>
    <link rel="stylesheet" href="{%static 'css/invoice-template-1.css' %}" media="all" />
  </head>
  <body>
    <header class="clearfix">
      <div id="logo">
        <img src="{% static 'img/logo.png'%}" style="width: 134px; height:116px"> 
      </div>
      <div id="company">
        <h1 class="name">{{company.name}}</h1>
        <div>{{company.address}}</div>
        <div>{{company.phone}}</div>
        <div><a href="mailto:{{company.email}}">{{company.email}}</a></div>
      </div>
      </div>
    </header>
    <main>
      <div id="details" class="clearfix">
        <div id="client">
          <div class="to">INVOICE TO:</div>
          <h2 class="name">{{customer}}</h2>
          <div class="address">{{billing_address}}</div>
          <div class="email"><a href="mailto:{{customer_email}}">{{customer_email}}</a></div>
        </div>
        <div id="invoice">
          <h1>#{{invoice_id}}</h1>
          <div class="date">Date of Invoice: {{date}}</div>
          <div class="date">Due Date: {{due_date}}</div>
        </div>
      </div>
      <table border="0" cellspacing="0" cellpadding="0">
        <thead>
          <tr>
            <th class="no">#</th>
            <th class="desc">DESCRIPTION</th>
            <th class="unit">RATE PER UNIT</th>
            <th class="qty">QUANTITY</th>
            <th class="total">TOTAL</th>
          </tr>
        </thead>
        <tbody>
			{% for item in lineitem %}
          <tr>
            <td class="no">{{forloop.counter}}</td>
            <td class="desc">{{item.description}}</td>
            <td class="unit">&#x20B9;{{item.rate}}</td>
            <td class="qty">{{item.quantity}}</td>
            <td class="total">&#x20B9;{{item.amount}}</td>
		  </tr>
		  {% endfor %}
        </tbody>
        <tfoot>
          <tr>
            <td colspan="2"></td>
            <td colspan="2">SUBTOTAL</td>
            <td>&#x20B9;{{invoice_total}}</td>
          </tr>
          <tr>
            <td colspan="2"></td>
            <td colspan="2">TAX 0%</td>
            <td>&#x20B9;{{invoice_total}}</td>
          </tr>
          <tr>
            <td colspan="2"></td>
            <td colspan="2">GRAND TOTAL</td>
            <td>&#x20B9;{{invoice_total}}</td>
          </tr>
        </tfoot>
      </table>
      <div id="thanks">Thank you for Shopping with us!</div>
    </main>
    <footer>
      Invoice was created on a computer and is valid without the signature and seal.
    </footer>
  </body>
</html>